### ISSUE TITLE
Unexpected behaviour caused by spawning an object in OnStartServer

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#112] opened 2022-09-23 15:41 UTC
### There is an unexpected/strange behavior that happens when trying to move an object and spawn another object in OnStartServer.
This is with "client authority" set in the Network Transform.
_Note: the object being moved is not the object being spawned._

If the call to spawn the object comes before the call to move, then the move does **not** happen effectively.
- The object will not move on its owner's client.
- The object will move on the server, and then instantly snap back.
- The object will move on other clients, and not snap back.

If however the call to spawn the object comes after the call to move, then the move **does** happen effectively.
- The object will move on the server and all clients.

Tested on FishNet versions 2.3.14 Pro and 2.4.5hf0 Pro.
_The problem does not happen for host clients._

Example of working code:
```cs
public override void OnStartServer()
{
    base.OnStartServer();

    GameObject go = Instantiate(prefab);

    // Setting this object's position, NOT the position of the spawned object.
    transform.SetPositionAndRotation(new Vector3(4, 4, 0), Quaternion.identity);

    InstanceFinder.ServerManager.Spawn(go);
}
```

Example of code not working:
```cs
public override void OnStartServer()
{
    base.OnStartServer();

    GameObject go = Instantiate(prefab);
    InstanceFinder.ServerManager.Spawn(go);

    // Setting this object's position, NOT the position of the spawned object.
    transform.SetPositionAndRotation(new Vector3(4, 4, 0), Quaternion.identity);
}
```
Here is a unitypackage with an example. The working version of the code is commented out.
[SpawnObjectTest.zip](https://github.com/FirstGearGames/FishNet/files/9635104/SpawnObjectTest.zip)

**Comment by maxkratt** [comment] 2022-09-24 22:11
Having now considered that moving an object on the server that has client authority is a pretty bad idea, I am ready to close this issue. However I'll wait for a response first in case this information could be helpful in tracking down a bug.

**Comment by FirstGearGames** [comment] 2022-09-24 22:13
You said its client auth but in your example you're not assigning an owner. If there is no owner the server should have say. 
If you are assigning an owner then the server won't have say at that point.

**Comment by maxkratt** [comment] 2022-09-25 05:48
So in the example I use the default player spawner component that comes with FishNet, this does set an owner unless I'm mistaken.

**Comment by FirstGearGames** [comment] 2022-09-26 17:46
It sounds like it's working as intended then.

You are moving the object before network spawning in one example, which updates the position on the server properly you stated. This makes sense because there is no owner at the time.

In your second example you're doing it after server spawning, where an owner has been set. Because you are using a NT with client authoritative and there is an owner, server no longer has say of the position, that owner does. Therefor the position you set on the server is properly being ignored.

**Comment by maxkratt** [comment] 2022-09-26 19:35
I think there is a misunderstanding, but I'll ask this. When OnServerStart is called on an object that has an owner set in its spawn call, doesn't the object already have an owner?
The following is where I think the misunderstanding is. The object being spawned in the script is not the object being moved. The object being spawned is irrelevant, all that's important in the example is the fact that spawning an object affects the outcome of the rest of the code in the script.

**Comment by FirstGearGames** [comment] 2022-09-26 23:34
> I think there is a misunderstanding, but I'll ask this. When OnServerStart is called on an object that has an owner set in its spawn call, doesn't the object already have an owner? The following is where I think the misunderstanding is. The object being spawned in the script is not the object being moved. The object being spawned is irrelevant, all that's important in the example is the fact that spawning an object affects the outcome of the rest of the code in the script.

You're right I missed that. This behavior is unusual.

**Comment by FirstGearGames** [comment] 2022-12-04 22:03
Confirmed unusual behavior. Marking as bug until I can investigate further.

**Comment by FirstGearGames** [comment] 2023-01-29 16:52
On the playerObj it would seem OnSpawnServer is being called before the position is changed. It's possible spawning another object is forcing the OnSpawnServer to invoke before OnStartServer finishes.

I've not dug deep enough but I suspect by spawning another object observers are being rebuilt immediately rather than after OnStartServer, which is why OnSpawnServer is being sent before the method completes.

I've yet to confirm this theory but it makes sense. I'm not sure how easy a fix for this will be but I'm keeping this bug on my radar.

**Comment by FirstGearGames** [comment] 2023-02-06 23:21
I'm putting this as wont fix. Maybe will come back to it later but seems like a minor issue and may require a bit of work I'm not ready to put in yet.

**Closed by FirstGearGames** 2023-02-06 23:21 UTC
Labels: bug
