### ISSUE TITLE
All CSP objects stop updating when one is not calling the [Replicate] method.

### ISSUE THREAD

**Issue by tedbarth** [FirstGearGames/FishNet#295] opened 2023-03-13 08:01 UTC
Unity version: 2021.3.19f1
Fish-Networking version: 3.4.3

**Describe the bug**
When stopping to call the [Replicate] method on one client, no CSP object (including those from other players) are updated, neither its main, nor graphical object.

**To Reproduce**
1. Implement CSP with PredictedObject with option to pause calling [Recoil]
```
  public bool paused = false;

  protected override void OnNetworkTick() {
    if (IsOwner) {
      Reconcile(default, false);

      float currentHorizontalInput = Input.GetAxisRaw("Horizontal");
      float currentVerticalInput = Input.GetAxisRaw("Vertical");

      MoveData md = default;
      md.Horizontal = currentHorizontalInput;
      md.Vertical = currentVerticalInput;

      if (!paused) {
        // Will be replicated on the server
        Move(md, false);
      }
    }

    if (IsServer) {
      Move(default, true);
    }
  }
```
2. Connect with two clients to a server
3. Turn off calling [Replicate] for the player A on one client A
4. Rotate the player B using inputs on the client B
5. Observe the players A and B on client A

**Expected behavior**
The player B object on client A still updates

**What you see instead**
No CSP object is updated on client A.

**Video**
https://youtu.be/RV4hZVWFDi4

**Comment by FirstGearGames** [comment] 2023-03-13 11:21
Intended behavior assuming you're using RBs. No replicate means no
reconcile, so nothing can correct/update.

This behavior is changing in the future though.

**Comment by tedbarth** [comment] 2023-03-13 11:30
But I disabled replication only for the player object A. Why would the object B affected?

**Comment by FirstGearGames** [comment] 2023-03-14 12:37
The changes have not officially been announced with details but they are intended to be backwards compatibles. Since this is not a bug I'm closing this out. Discussions on the Discord please, thank you.

**Closed by FirstGearGames** 2023-03-14 12:37 UTC
