### ISSUE TITLE
SyncVar's "OnChange" is called only once in the host mode when setting a value before spawning object containing it (it's not cached for client)

### ISSUE THREAD

**Issue by kubpica** [FirstGearGames/FishNet#463] opened 2023-09-17 19:11 UTC
**General**
Unity version: 2021.3.21f1
Fish-Networking version: 3.11.0
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1153003298358575194

**Description**
SyncVar's "OnChange" is called only once when running in the host mode (server & client) with asServer true. In 2.5.10 it would be called twice - once with asServer true and second time with asServer false.

**Replication**
```cs
public class Test : NetworkBehaviour
{
    [SyncVar(OnChange = nameof(OnMySyncVarChange))]
    public int mySyncVar = 0;

    void OnMySyncVarChange(int old, int now, bool asServer)
    {
        Debug.Log($"OnMySyncVarChange: asServer = {asServer}");
    }
}

public class Test2 : MonoBehaviour
{
    public GameObject sthToSpawnWithTestScript;

    private void Update()
    {
        if (Input.GetKeyDown(KeyCode.J))
        {
            // Init
            GameObject go = Instantiate(sthToSpawnWithTestScript);
            var script = go.GetComponent<Test>();
            script.mySyncVar = 123;

            // Spawn
            if (InstanceFinder.IsServer)
                InstanceFinder.ServerManager.Spawn(go);
        }
    }
}
```
From what I see when `OnStartClientCalled` is false then the value is supposed to be cached and set after `OnStartClient`, but it's not cached because `InvokeOnChange(T prev, T next, bool asServer)` in SyncVar.cs is called only once with asServer true, so it caches only for server. Spawning before setting the value worked for me, but if setting SyncVars before an object is spawned is allowed feature then I think it's bug.
Edit: I found places in my code where changing it to spawn before initing the synced values is not that easy (without restructuring the code) so this bug affects me even more than I thought.

**Expected behavior**
The callback should be called twice when running in the host mode - once for server and once for client.

**Comment by FirstGearGames** [comment] 2023-09-20 18:19
Pretty sure this is working as intended and calling on both. SyncVars are taking a turn in v4 though where this shouldn't be a concern. So I'm going to leave this open only as a reminder to test for this in v4.

**Comment by kubpica** [comment] 2023-09-20 18:35
For me on v3.11.0 it's calling both (asServer true and false) only when I spawn the object before setting SyncVar, if I first set the value and then spawn it calls OnChange only once with asServer true. But ok, I can do workarounds with making sure that the object is first spawned before I set the value.

**Comment by FirstGearGames** [comment] 2023-09-20 18:56
I believe that's intended because it's assumed values are set before the
callbacks. But there's a new feature coming that might be helpful...
Planning on how to add it still.

Would be something like OnClientSyncTypes which will invoke after all, if
any synctypes are updated.

**Comment by kubpica** [comment] 2023-09-20 20:08
I feel like we don't understand each other, because I really think it's bug but I don't want to argue over such small thing. In v2.5.10 it would call SyncVars OnChange callback twice when in host mode, now it's called only once, so when I updated to v3.11.0 a lot of thing broke in my game, but I can fix it, no problem I just really tought it's bug so I wannted to report it.
Anyway, thank you for your work, Fishnet is awesome!

**Comment by FirstGearGames** [comment] 2023-09-20 20:15
I'll run some tests after the v4 updates to make sure it's working as it
should. Not much reason to in v3 though since the v4 update is coming soon.

**Comment by FirstGearGames** [comment] 2023-10-02 15:47
I tested in v4 setting the value in OnStartServer, which did invoke the change on server and clientHost after the client connected.
Your approach should do the same given if the value is set anytime after Awake the value will be invoked on both.

While it is probably safe to say this is working in v4 I've not tested your situation **exactly** so I will do that and let you know of the results. In the mean time I just wanted to update you with my findings.

**Comment by FirstGearGames** [comment] 2023-10-04 18:09
> ...
This code is working in my tests. Can you please validate in your project and test scene to see if you are getting the same results.
```cs
        public void SetValue(T nextValue, bool calledByUser)
        {
            /* If not registered then that means Awake
             * has not completed on the owning class. This would be true
             * when setting values within awake on the owning class. Registered
             * is called at the end of awake, so it would be unset until awake completed.
             * 
             * Registered however will be true when setting from another script,
             * even if the owning class of this was just spawned. This is because
             * the unity cycle will fire awake on the object soon as it's spawned, 
             * completing awake, and the user would set the value after. */
            if (!base.IsRegistered)
                return;

            /* If not client or server then set skipChecks
             * as true. When neither is true it's likely user is changing
             * value before object is initialized. This is allowed
             * but checks cannot be processed because they would otherwise
             * stop setting the value. */
            bool isNetworkInitialized = base.IsNetworkInitialized;

            //Object is deinitializing.
            if (isNetworkInitialized && CodegenHelper.NetworkObject_Deinitializing(this.NetworkBehaviour))
                return;

            //If being set by user code.
            if (calledByUser)
            {
                if (!base.CanNetworkSetValues(true))
                    return;

                /* We will only be this far if the network is not active yet,
                 * server is active, or client has setting permissions. 
                 * We only need to set asServerInvoke to false if the network
                 * is initialized and the server is not active. */
                bool asServerInvoke = (!isNetworkInitialized || base.NetworkBehaviour.IsServer);

                T prev = _value;

                /* If the network has not been initialized yet then the
                 * object has not yet spawned. While we know this is being called
                 * from user code, because the object is not spawned we do not
                 * know if server or client is active. When this happens invoke
                 * will be called on server and client, and since this is not
                 * network initialized the values will be cached where the invoke
                 * will occur after spawn. */
                if (!isNetworkInitialized)
                {
                    //Value did not change.
                    if (Comparers.EqualityCompare<T>(_value, nextValue))
                        return;

                    _value = nextValue;
                    InvokeOnChange(prev, _value, true);
                    InvokeOnChange(prev, _value, false);
                }
                else
                {
                    //Value did not change.
                    if (Comparers.EqualityCompare<T>(_value, nextValue))
                        return;

                    _value = nextValue;
                    InvokeOnChange(prev, _value, asServerInvoke);
                }

                TryDirty(asServerInvoke);
            }
            //Not called by user.
            else
            {
                /* Previously clients were not allowed to set values
                 * but this has been changed because clients may want
                 * to update values locally while occasionally
                 * letting the syncvar adjust their side. */
                T prev = _previousClientValue;
                if (Comparers.EqualityCompare<T>(prev, nextValue))
                    return;

                /* If also server do not update value.
                 * Server side has say of the current value. */
                if (!base.NetworkManager.IsServer)
                    UpdateValues(nextValue);
                else
                    _previousClientValue = nextValue;

                InvokeOnChange(prev, nextValue, calledByUser);
            }


            /* Tries to dirty so update
             * is sent over network. This needs to be called
             * anytime the data changes because there is no way
             * to know if the user set the value on both server
             * and client or just one side. */
            void TryDirty(bool asServer)
            {
                //Do not mark dirty if the object is not been network initialized.
                if (!isNetworkInitialized)
                    return;

                if (asServer)
                    base.Dirty();
            }
        }

        /// <summary>
        /// Invokes OnChanged callback.
        /// </summary>
        private void InvokeOnChange(T prev, T next, bool asServer)
        {
            if (asServer)
            {
                if (base.NetworkBehaviour.OnStartServerCalled)
                {
                    OnChange?.Invoke(prev, next, asServer);
                    _serverOnChange = null;
                }
                else
                    _serverOnChange = new CachedOnChange(prev, next);
            }
            else
            {
                if (base.NetworkBehaviour.OnStartClientCalled)
                {
                    OnChange?.Invoke(prev, next, asServer);
                    _clientOnChange = null;
                }
                else
                {
                    _clientOnChange = new CachedOnChange(prev, next);
                }
            }
        }

```

**Comment by kubpica** [comment] 2023-10-04 19:30
After updating the SyncVar.cs I get null reference exception (when I click J - I used the code in the first post to test it)
![image](https://github.com/FirstGearGames/FishNet/assets/14114440/2bbf8991-56af-4555-a506-c2d948095901)

**Comment by FirstGearGames** [comment] 2023-10-05 12:29
I assume as clientHost? I am not receiving the error, can you please update to 3.11.2 and if the error persist send me the package with just the files you are testing.

**Comment by FirstGearGames** [comment] 2023-10-05 14:37
I suspect this might be a one-shot instance where something wasn't right with your Unity, maybe a recompile fail or something.
Let me know what you find out and I'll investigate.

**Comment by kubpica** [comment] 2023-10-07 11:57
I imported 3.11.2 to empty project and yes it works now :) Thanks.

**Comment by FirstGearGames** [comment] 2023-10-07 12:11
Glad to hear it!

**Closed** 2023-10-13 18:08 UTC
Labels: Acknowledged, Resolved Pending Release
