### ISSUE TITLE
3.11.5hf0 NT not spawning or syncing scene object when giving it ownership

### ISSUE THREAD

**Issue by celojevic** [FirstGearGames/FishNet#516] opened 2023-10-26 15:10 UTC
**General**
Unity version: 2021.3.27 LTS
Fish-Networking version: 3.11.5hf0 (latest at the time of writing)
Discord link: https://discord.com/channels/424284635074134018/1166750663015923834/1166756244300763176

**Description**
When having a globally loaded scene object with a default NT on it, network object, and net observer with only a scene condition, it gives some spawning warnings (see screenshot 1). I believe this is causing the NT not to sync to clients (nor from client to host if they are the owner). This occurs with both host and client-only.

**Replication**
1. Make a scene object with an NT, nob, and net observer with only a scene condition as well as a simple controller script.
2. Globally load this scene and give one of multiple connections ownership of it. Im doing it in the client presence change callback
```cs
private void SceneManager_OnClientPresenceChangeEnd(ClientPresenceChangeEventArgs obj)
        {
            if (!obj.Added || gameObject.scene != obj.Scene) return;
            if (RefMan.I.WielderController.Owner != obj.Connection) return;

            // give wielder the control over the cursor
            base.GiveOwnership(RefMan.I.WielderController.Owner);
        }
```
3. You will get the warnings and the NT wont sync to clients.

**Expected behavior**
Ownership change shouldnt throw warnings and the NT should sync position.

**Screenshots**
Screenshot 1:
![image](https://github.com/FirstGearGames/FishNet/assets/61945370/c7f95c61-338c-4b81-b425-26884475068f)

**Comment by FirstGearGames** [comment] 2023-10-27 19:26
Thanks gooby. I'll take a look **after** 3.11.6 release.

**Comment by FirstGearGames** [comment] 2023-10-28 12:21
Issue confirmed but does not seem to be related to any component. Seems to be an error with the client parsing packets under these conditions.

**Comment by FirstGearGames** [comment] 2023-11-08 15:39
Lowered priority.

**Comment by FirstGearGames** [comment] 2024-04-04 00:39
This does not seem to be a problem in V4. Closing out!

**Closed by FirstGearGames** 2024-04-04 00:39 UTC
Labels: Bug, Low Priority
