### ISSUE TITLE
Using FishySteamworks on disconnect throws Error TransportIdData could not be found for Multiass connectionId of 0.

### ISSUE THREAD

**Issue by KZkici** [FirstGearGames/FishNet#106] opened 2022-09-14 22:24 UTC
Start Host/Client, 
Disconnect:

		if (InstanceFinder.IsServer)
		{
			InstanceFinder.ServerManager.StopConnection(true);
		}
		else if (InstanceFinder.IsClient)
		{
			InstanceFinder.ClientManager.StopConnection();
		}

Throws error:

TransportIdData could not be found for Multiass connectionId of 0.
UnityEngine.Debug:LogError (object)
FishNet.Transporting.Multipass.Multipass:SendToClient (byte,System.ArraySegment`1<byte>,int) (at Assets/FishNet/Runtime/Transporting/Transports/Multipass/Multipass.cs:454)
FishNet.Managing.Transporting.TransportManager:IterateOutgoing (bool) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:410)
FishNet.Managing.Timing.TimeManager:TryIterateData (bool) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:960)
FishNet.Managing.Timing.TimeManager:IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:710)
FishNet.Managing.Timing.TimeManager:TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:361)
FishNet.Transporting.NetworkReaderLoop:Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)

Note: The debug error does indeed say Multiass :)
I just realized that lol

**Comment by Abdelfattah-Radwan** [comment] 2022-09-24 15:02
> I cannot reproduce. Steps:
> 
> * New scene.
> * Added NetworkManager prefab.
> * Added Multipass and set it as the transport in TransportManager.
> * Added FishySteamworks and set it as a transport in Multipass.
> * Added SteamManager.
> * Hit play, started server then client using prefab HUD.
> * Stopped server using prefab HUD.
> 
> Both server and client stop without error.

Interesting...

I can reproduce the issue using the same steps above even on the latest version of Fish-Networking.

**Comment by FirstGearGames** [comment] 2022-09-26 17:47
Winterbolt said he wasn't able to reproduce in the latest. I was not either naturally. Going to close this, please re-open if the problem persist.

**Closed by FirstGearGames** 2022-09-26 17:47 UTC
Labels: bug, Resolved

**Comment by lordubbe** [comment] 2022-09-26 19:17
I get this error as well in 2.5.1 Pro, so I am afraid it might be too early to close the issue.
I haven't tried to see if the issue reproduces given the steps provided as the setup is a bit different in my game.

Not sure if it's related, but my Multipass setup includes Yak and FishyFacepunch transports. What I do to reproduce the error is:

1. Set the transport to FishyFacepunch
2. Start the server using ServerManager.StartConnection
3. ClientManager.StopConnection + ServerManager.StopConnection (only if server)

![image](https://user-images.githubusercontent.com/6771203/192360529-59dba264-6bd5-4655-81a2-0522055c9e7b.png)
Some of the logs are not relevant - aplogies for this, just thought I'd share since I stumbled over this issue :)
