### ISSUE TITLE
ObserversRPC not working for SceneObject.

### ISSUE THREAD

**Issue by Stormhound** [FirstGearGames/FishNet#316] opened 2023-04-01 10:06 UTC
Unity version:
Fish-Networking version: 3.5.7 Pro

**Describe the bug**
I have SceneObject on another scene. Whenever I loaded scene for Clients I subscribe for event  on server to acknowledge if Client loaded scene. Whenever that event fired I'm trying to send ObserversRPC but its not always working. Someone said it could be that client was not observing yet while I'm sending ObserversRPC. But I checked SceneConditions is met before sending RPC.

**To Reproduce**
1. Create separate scene and add NetworkedObject to GameObject.
2. Add custom script to that NetworkedObject and subscribe to SceneManager_OnClientPresenceChangeEnd.
3. Whenever SceneManager_OnClientPresenceChangeEnd fired check for SceneCondition and try to send ObserversRPC inside that script.

**Expected behavior**
It should be sending rpc to all observers because client were already observing and meeting condition.

**Comment by FirstGearGames** [comment] 2023-04-16 15:05
I was not able to replicate with just a SceneCondition but could force a SceneId not found error through other means. 

To get the error I had to include a timed condition (I used distance, object in range when scene loaded), and scene condition.
It seems there's a few unique steps needed to replicate the error I got.

1. Timed conditions must be placed before non-timed. EG: DistanceCondition would be index 0 in conditions, while SceneCondition was index 1.
2. The scene must already be loaded on the server before client only joins.  EG: not loaded because the client joined, but already loaded.

If you have timed conditions try putting them at the bottom of conditions and let me know if that resolves the problem.
This is definitely a bug though, I'll get it resolved. Thanks!

**Comment by Stormhound** [comment] 2023-04-16 16:22
If MatchCondition counts as you called "timed condition" then yeah I probably ran into same bug.

**Comment by FirstGearGames** [comment] 2023-04-16 16:47
MatchCondition is not a timed condition. So the problem may occur with just more than one condition. Either way, I confirmed the issue and will get it resolved. Thanks for the find.

**Comment by FirstGearGames** [comment] 2023-05-16 15:21
Following up: I've made many changes and fixes to the observer system but this still seems to be present. Will have it resolved by 3.7.0

**Comment by FirstGearGames** [comment] 2023-05-16 16:26
I found a number of scenarios which could cause this but only one was actually a bug, and it's been resolved.

Prior to the fix the NetworkObserver was flagging a connection as meeting all non-timed conditions when a timed one would pass before failing non-timed ones. In result future checks were not checking non-timed conditions, such as scene condition, and only distance. Because the object was in range of the player on the server even though the player was not in the scene, this would pass and try to spawn the object for the player.

The second reason, though I imagine very possibly a common one, is setup error. If you were to have 'add to default scenes' checked on the playerspawner and the object spawned into a scene the player did not have loaded then they would also receive errors. Solution to this one is make sure if using the playerspawner with add to default scenes enabled, to only spawn the player in the scenes they could see. Or more simply, don't set the active scene on the server to one which all clients may not be in.

Either way this is indeed resolved now in 3.7

**Closed** 2023-05-17 18:26 UTC
Labels: Bug, Resolved Pending Release, Priority
