### ISSUE TITLE
Rigidbody prediction doesn't work on host

### ISSUE THREAD

**Issue by Maclay74** [FirstGearGames/FishNet#262] opened 2023-02-16 18:31 UTC
Unity version: 2022.2
Fish-Networking version: 3.2.2

**Describe the bug**
GameObject with Rigidbody doesn't move smoothly with the correct `PredictedObject` setup. 
It's mostly noticeable with very low tick rate.  

**To Reproduce**
1. Open default example scene with rigidbody prediction
2. Create a new object, add `Rigidbody` and `BoxCollider` to it
3. Add Box to it as a child
4. Add `PredictedObject` and assign Box as visual object, use Rigidbody type prediction
5. Set low tick rate, like 5
6. Run the game and try to move the object

**Expected behavior**
Object should move smoothly on both hosts and clients. Tick rate shouldn't affect smoothness. 

**Screenshots**

https://user-images.githubusercontent.com/5504685/219455735-59c4e304-3bec-4274-b109-a905ac5378e3.mp4

**Comment by FirstGearGames** [comment] 2023-02-17 15:25
Prediction is working but the smoothing is not. Seems to be with either unowned objects or unowned scene objects. Maybe objects that do not implement replicate/reconcile. Either way, confirmed bug. I'll have it resolved soon.

**Comment by FirstGearGames** [comment] 2023-02-17 16:42
Resolved in 3.3.4 which will be published today or tomorrow.
Change these methods in `PredictedObject.cs`

```

        public override void OnStartClient()
        {
            base.OnStartClient();
            ChangeSubscriptions(true);
            Rigidbodies_OnStartClient();
        }
```
```

        public override void OnStartNetwork()
        {
            base.OnStartNetwork();

            /* If host then initialize owner smoother.
             * Host will use owner smoothing settings for more
             * accurate results. */
            if (base.IsHost)
                InitializeSmoother(true);

            UpdateRigidbodiesCount(true);
            ConfigureRigidbodies();
            ConfigureNetworkTransform();
            base.TimeManager.OnPostTick += TimeManager_OnPostTick;
        }
```

**Closed** 2023-02-25 14:58 UTC
Labels: bug, Resolved Pending Release
