### ISSUE TITLE
NetworkAnimator not syncing first call when set to server auth

### ISSUE THREAD

**Issue by maxkratt** [FirstGearGames/FishNet#218] opened 2023-01-10 12:55 UTC
Unity version: 2021.3.16f
Fish-Networking version: 2.6.6.Pro and 3.1.1.Pro

**Describe the bug**
When using the NetworkAnimator set to `server auth` and `send to owner`, the animations aren't played on clients when the first call to NetworkAnimator.Play is made. The animations are only played on the server; It takes another call for the animation to be correctly played on all clients. 

**To Reproduce**
1. Have a couple of basic animations for the player.
2. Setup an Animator and NetworkAnimator.
3. Choose server auth and send to owner on the NetworkAnimator.
4. Play an animation on the NetworkAnimator.

**Expected behavior**
In FishNet 2.5.8.Pro the animation would sync to all clients on the first attempt.

Here is the script I used to test the animations:
```cs
using FishNet.Component.Animating;
using FishNet.Object;
using TriInspector;
using UnityEngine;

public class AnimTester : NetworkBehaviour
{
    [SerializeField, OnValueChanged(nameof(ServerPlayMove))] bool playMove;
    [SerializeField, OnValueChanged(nameof(ServerPlayIdle))] bool playIdle;
    [SerializeField] NetworkAnimator anim;

    [ServerRpc]
    public void ServerPlayIdle()
    {
        anim.Play("idle");
    }

    [ServerRpc]
    public void ServerPlayMove()
    {
        anim.Play("move");
    }
}
```

**Comment by FirstGearGames** [comment] 2023-01-10 14:13
We only support the latest version of major releases. Test would have to be
run on 2.6.6 or 3.1.1

**Comment by maxkratt** [comment] 2023-01-10 14:42
Oh, perhaps there's a misunderstanding. Those are the versions I tested on

**Comment by Katerlad** [comment] 2023-01-11 23:33
FGG has leveled up his document skimming skill to level 79, he is still working towards 99 so be patient. 😉 lol lol

**Comment by FirstGearGames** [comment] 2023-01-11 23:38
Lol I'm sorry it's partially because I view the issues inside my email and
I don't catch everything. It's good information to know which version it
worked on.

 Thank you very much for that.

**Comment by FirstGearGames** [comment] 2023-01-29 15:22
I was unable to reproduce. I created a player prefab with a basic animator that has a 'Jump' animation. On that player I added NetworkAnimator component, unchecked client authoritative, checked send to owner.

Added the following script...
```
using FishNet.Component.Animating;
using FishNet.Object;
using UnityEngine;

public class NetworkAnimator_ServerAuth_Play_Test : NetworkBehaviour
{

    private NetworkAnimator _networkAnimator;

    private void Awake()
    {
        _networkAnimator = GetComponent<NetworkAnimator>();
    }

    private void Update()
    {
        if (!base.IsServer)
            return;

        if (Input.GetKeyDown(KeyCode.LeftShift))
            _networkAnimator.Play("Jump");
    }
}
```
Started server, started client in different instances. Pressed LeftShift on server. 
Jump animation ran on server and client.

**Comment by maxkratt** [comment] 2023-01-29 16:10
Ok, thank you for checking. I'll have another look on the latest version with the code you used and write back with the results.

**Comment by maxkratt** [comment] 2023-01-29 20:35
Well, after having a look at it again, it is rather weird. Something to do with the Unity inspector, but I have no clue as to why.
Previously I was using TriInspector's OnValueChanged attribute to call a server rpc to play the animation, but I am able to recreate the issue without it. Namely, by using a normal bool set from the inspector and watched for from the Update method that sends the rpc.

Here is the code I used now. The comments mention the strange behavior.
```cs
using FishNet.Component.Animating;
using FishNet.Object;
using UnityEngine;

public class AnimTester : NetworkBehaviour
{
    [SerializeField] bool serverPlayIdle; 

    [ServerRpc]
    public void ServerPlayIdle()
    {
        GetComponent<NetworkAnimator>().Play("idle");
    }

    [ServerRpc]
    public void ServerPlayMove()
    {
        GetComponent<NetworkAnimator>().Play("move");
    }

    private void Update()
    {
        if (!IsOwner) return;

        // This works, but toggling the serverPlayIdle bool in the inspector does not for some reason.
        if (Input.GetKey(KeyCode.H))
            serverPlayIdle = true;

        // This works when the bool is not set from the inspector.
        if (serverPlayIdle)
        {
            serverPlayIdle = false;
            ServerPlayIdle();
        }

        // This works fine
        if (Input.GetKey(KeyCode.M))
            ServerPlayMove();
    }
}
```
It might just be a Unity problem I suppose. 🤷‍♂️

**Comment by FirstGearGames** [comment] 2023-01-29 20:40
Alright, closing out then!

**Closed by FirstGearGames** 2023-01-29 20:40 UTC
Labels: unable to reproduce
