### ISSUE TITLE
Network transform not able to receive and sync data in webgl (chrome)

### ISSUE THREAD

**Issue by AviMersiv** [FirstGearGames/FishNet#614] opened 2024-02-26 15:10 UTC
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2022.3.30f1
Fish-Networking version: 3.11.16R
Discord link: https://discord.com/channels/424284635074134018/1034477094731784302/1211676546868318249
** Above, post a link from our Discord where you troubleshot the issue (on Discord click the three dots next to the message, then Copy Message Link). Issue may be closed out if this is not included.

**Description**
Hi My project is mainy for webgl (not editor) mainly working on chrome/edge/safari
I created a simple scene with 2 players both having network transform 
I run the server on local host , and 1st client via the unity editor 
2nd client via web local host (chrome)

the bug im facing :
when the player in chrome aka 2nd client is moving the 1st client aka editor is being able to get the data from him and sync his movements (via the network transform component)
but when i try the other way around moving from editor and receiveng in webgl I get instant exception in webgl 
`MissingMethodException: Default constructor not found for type FishNet.Component.Transforming.NetworkTransform+GoalData`
for some reason the goaldata under the network transform is not being transfared correctly

**Replication**
1. make a simple prefab with network transform and network object components
2. make simple scene with netwrok manager and add the prefab under the player spawner
3. build dedicated server to run on local host
4. run editor as client
5. build webgl and run as 2nd client
6. move in editor and bug should be reproduced data wont transfar and there will be network transform goal data exception in chrome

**Expected behavior**
expected will be that movement from the editor will be able to sync to the webgl 
just as expected from the network transform component

**Screenshots**

![image](https://github.com/FirstGearGames/FishNet/assets/135507345/645db1e5-99d4-4596-a75b-0b60bd08c766)

**Comment by FirstGearGames** [comment] 2024-03-20 15:30
This is caused by Unity stripping code.

I'll get this resolved in the next few days. In the mean time you can fix it yourself by adding this...
```cs
[Preserve]
```
Above the following like so:
```cs
            [Preserve]
            public RateData() { }
            [Preserve]
            public GoalData() { }
```

**Closed** 2024-04-10 01:13 UTC
Labels: Bug, Resolved Pending Release
