### ISSUE TITLE
Destroy / Disable nob bug

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#649] opened 2024-04-13 13:58 UTC
**General**
Unity version: 2021.3.30f1
Fish-Networking version: 4.2.0 Pro
Discord link:
https://discord.com/channels/424284635074134018/1034477094731784302/1228664103296303166

**Description**
After update my main project from 3.x version to 4.2.0, i start to have weird thing. I have items and enemies in game. Enemies nob started to not despawn. I faced situation when ResetState for SyncVars called, but gameobject nob not disabled (enemies nobs pooled, but also true for simple destroy). Ive found that it happens only at Host. And idk how to replicate it, because items nobs working fine. I did expose some values from ManagedObjects.cs and log them to console. just added 2 vars for tracking `NetworkManager.ServerManager.Objects.AddToPending(nob);` and `NetworkManager.ServerManager.Objects.RemoveFromPending(nob.ObjectId);`
code: 
`Debug.Log($"destroy: {destroy}, nested: {nob.IsNested}, asServer: {asServer}, IsSceneObject: {nob.IsSceneObject}, AddToPending: {addToPending}, RemoveFromPending: {removeFromPending}");`
here is a log of this issue: 
`destroy: False, nested: False, asServer: False, IsSceneObject: False, AddToPending: False, RemoveFromPending: False`
This log calling once (edited) per each nob.

I checked how this log working in normal case, and it should have asServer true, or AddToPending true, and RemoveFromPending true on next call, but it never happens in Host for some reason

**Expected behavior**
nobs disabling or destroying depends of pool or derstroy setting

**Screenshots**
[Video](https://drive.google.com/file/d/1uacn0WnPXeCBwD3rpbcP0HdQR-O1th05/view?usp=sharing)

**Comment by SnaiperoG3D** [comment] 2024-04-29 18:32
still happens in 4.2.2, which prevents it from working properly in single player

**Comment by SnaiperoG3D** [comment] 2024-04-30 09:06
new issue in 4.2.2.
i believe both somehow connected to each other
NRE in NetworkObject.cs:842

**Comment by FirstGearGames** [comment] 2024-05-04 20:02
A recent callback fix was applied for this https://github.com/FirstGearGames/FishNet/issues/652

I'll send you an update via DM to try. Let me know if it fixes.

**Comment by SnaiperoG3D** [comment] 2024-05-27 16:00
Duplicate from Discord. 
No update not resolve the issue, also i have a little more info about it. I believe that it related. There are 2 errors happens when despawn should occur:
`NullReferenceException: Object reference not set to an instance of an object
FishNet.Object.NetworkObject.Deinitialize (System.Boolean asServer) (at Assets/FishNet/Runtime/Object/NetworkObject.cs:858)
FishNet.Managing.Object.ManagedObjects.Despawn (FishNet.Object.NetworkObject nob, FishNet.Object.DespawnType despawnType, System.Boolean asServer) (at Assets/FishNet/Runtime/Managing/Object/ManagedObjects.cs:162)
FishNet.Managing.Client.ClientObjectCache.IterateDespawn (FishNet.Managing.Client.CachedNetworkObject cnob) (at Assets/FishNet/Runtime/Managing/Client/Object/ObjectCaching.cs:495)
FishNet.Managing.Client.ClientObjectCache.<Iterate>g__ProcessObject|14_0 (FishNet.Managing.Client.CachedNetworkObject cnob, System.Boolean spawn, System.Int32 index, FishNet.Managing.Client.ClientObjectCache+<>c__DisplayClass14_0& ) (at Assets/FishNet/Runtime/Managing/Client/Object/ObjectCaching.cs:411)
FishNet.Managing.Client.ClientObjectCache.Iterate () (at Assets/FishNet/Runtime/Managing/Client/Object/ObjectCaching.cs:279)
FishNet.Managing.Client.ClientObjects.IterateObjectCache () (at Assets/FishNet/Runtime/Managing/Client/Object/ClientObjects.cs:495)
FishNet.Managing.Client.ClientManager.ParseReader (FishNet.Serializing.PooledReader reader, FishNet.Transporting.Channel channel, System.Boolean print) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:539)
FishNet.Managing.Client.ClientManager.ParseReceived (FishNet.Transporting.ClientReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:384)
FishNet.Managing.Client.ClientManager.Transport_OnClientReceivedData (FishNet.Transporting.ClientReceivedDataArgs args) (at Assets/FishNet/Runtime/Managing/Client/ClientManager.cs:342)
FishNet.Transporting.Tugboat.Tugboat.HandleClientReceivedDataArgs (FishNet.Transporting.ClientReceivedDataArgs receivedDataArgs) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:238)
FishNet.Transporting.Tugboat.Client.ClientSocket.IterateIncoming () (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Core/ClientSocket.cs:295)
FishNet.Transporting.Tugboat.Tugboat.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Transporting/Transports/Tugboat/Tugboat.cs:211)
FishNet.Managing.Transporting.TransportManager.IterateIncoming (System.Boolean server) (at Assets/FishNet/Runtime/Managing/Transporting/TransportManager.cs:705)
FishNet.Managing.Timing.TimeManager.TryIterateData (System.Boolean incoming) (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:1017)
FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:670)
FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|98_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:342)
FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:332)
FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)`

`NullReferenceException: Object reference not set to an instance of an object
FishNet.Component.Transforming.NetworkTransform.TimeManager_OnPostTick () (at Assets/FishNet/Runtime/Generated/Component/NetworkTransform/NetworkTransform.cs:947)
FishNet.Managing.Timing.TimeManager.IncreaseTick () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:688)
FishNet.Managing.Timing.TimeManager.<TickUpdate>g__MethodLogic|98_0 () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:342)
FishNet.Managing.Timing.TimeManager.TickUpdate () (at Assets/FishNet/Runtime/Managing/Timing/TimeManager.cs:332)
FishNet.Transporting.NetworkReaderLoop.Update () (at Assets/FishNet/Runtime/Transporting/NetworkReaderLoop.cs:28)`

**Comment by SnaiperoG3D** [comment] 2024-05-28 16:32
ok, well, i didt find the point of the problem, but i believe i did find a temp fix. I did a wrap for ClientManager for null check in NetworkObject.cs script at 858 line
`                if(ClientManager != null)
                {
                    Dictionary<NetworkObject, NetworkConnection.LevelOfDetailData> currentLods = ClientManager.Connection.LevelOfDetails;
                    if (currentLods.TryGetValue(this, out NetworkConnection.LevelOfDetailData lodData))
                        ObjectCaches<NetworkConnection.LevelOfDetailData>.Store(lodData);
                    ClientManager.Connection.LevelOfDetails.Remove(this);

                    //Client only.
                    if (!NetworkManager.IsServerStarted)
                        IsDeinitializing = true;

                    RemoveClientRpcLinkIndexes();
                }`
                
Not despawn / destroy fix still in process, cuz idk the internal fish logic

**Comment by SnaiperoG3D** [comment] 2024-05-28 21:02
Well. I have some moe info about it. I did inverstigate into fish code and found something interesting. Need to say about bug, whats happening again: some nobs go not disabling, but syncvars reseted. I thought why its happening not for all nobs, cuz i have items and enemies, with items everything is ok, but enemies go are not disabling. After temp bug fix i found that it happens only with items, because of despawning system, and i did compare with enemy despawn system, it works in different way. If items despawning almost at same time as distance condition despawn it, enemies despawning in another way. This logic has 10 sec cooldown. I did compare last fish NetworkObject.cs revision with some older versions in my VC, and ive found next:
new one:
```c#
        /// <summary>
        /// Called to prepare this object to be destroyed or disabled.
        /// </summary>
        internal void Deinitialize(bool asServer)
        {
#if !PREDICTION_1
            Prediction_Deinitialize(asServer);
#endif
            InvokeStopCallbacks(asServer, true);
            for (int i = 0; i < NetworkBehaviours.Length; i++)
                NetworkBehaviours[i].Deinitialize(asServer);

            if (asServer)
            {
                NetworkObserver?.Deinitialize(false);
                IsDeinitializing = true;
            }
            else
            {
                Dictionary<NetworkObject, NetworkConnection.LevelOfDetailData> currentLods = ClientManager.Connection.LevelOfDetails;
                if (currentLods.TryGetValue(this, out NetworkConnection.LevelOfDetailData lodData))
                    ObjectCaches<NetworkConnection.LevelOfDetailData>.Store(lodData);
                ClientManager.Connection.LevelOfDetails.Remove(this);
                //Client only.
                if (!NetworkManager.IsServerStarted)
                    IsDeinitializing = true;

                RemoveClientRpcLinkIndexes();
            }

            SetInitializedStatus(false, asServer);

            if (asServer)
                Observers.Clear();
        }
```

old one: 
```c#
        /// <summary>
        /// Called to prepare this object to be destroyed or disabled.
        /// </summary>
        internal void Deinitialize(bool asServer)
        {
            InvokeStopCallbacks(asServer);
            if (asServer)
            {
                IsDeinitializing = true;
            }
            else
            {
                //Client only.
                if (!NetworkManager.IsServer)
                    IsDeinitializing = true;

                RemoveClientRpcLinkIndexes();
            }

            SetActiveStatus(false, asServer);
            if (asServer)
                Observers.Clear();
        }
```

We interested in this lines:
```c#
 for (int i = 0; i < NetworkBehaviours.Length; i++)
                NetworkBehaviours[i].Deinitialize(asServer);
```
They do reset SyncVars inside their logic.

So i believe whats happening: enemies despawning with DistanceCondition, but only for "client" (remember we talking about host, cuz bug only here), on "server" side enemies still exist, BUT this lines do reset for SyncVars, and when my spawning system want to despawn enemies, it catch NRE cuz it using SyncVar to identify enemy, but SyncVar already reseted. Thats why it happening only with enemies, cuz i dont use syncvars in items logic and go not setted to false, cuz enemies still exist on "server" side.

So as a result i believe that bug with Reset SyncVars on host for client, when distance condition worked, what do reset for server side, cuz it host.

**Comment by SnaiperoG3D** [comment] 2024-05-29 09:37
Well, i guess ive found a temp fix for this bug too. I did wrap for these lines with checks for !asServer and for host. Idk is it break something or not, but now my games start to work in singleplayer atleast.
```c#
            if(!asServer && !NetworkManager.IsHostStarted)
                for (int i = 0; i < NetworkBehaviours.Length; i++)
                    NetworkBehaviours[i].Deinitialize(asServer);
```

**Comment by FirstGearGames** [comment] 2024-05-31 20:42
Going off what you read I'm understanding the end point of your issue is that the SyncVar is resetting on the Deinitialize server logic, and by that clearing the value it's affecting the clientHost.

If this is correct can you explain or show me a little more how you are using the SyncVar in relation to what is causing your error?


PS: if I may make a recommendation of something to try as a temp fix instead of the route you took ...
go into the SyncVar.cs file and change the ResetState method to this...
```cs

        internal protected override void ResetState(bool asServer)
        {
            base.ResetState(asServer);

            //Let clientHost reset if the object containing this syncvar is initialized for them.
            if (asServer && base.IsNetworkInitialized && NetworkBehaviour.IsClientInitialized)
                return;

            _value = _initialValue;
            _previousClientValue = _initialValue;
        }
```

**Comment by SnaiperoG3D** [comment] 2024-06-13 16:29
No, this code doesnt help, plus SyncVar never reset now

**Comment by FirstGearGames** [comment] 2024-07-01 13:41
This seems to be a very unique use-case issue. I'm having no luck seeing any obvious problem at this time and am not able to replicate. If you have this problem on 4.3.5+ can you please DM me on Discord so we can resolve it in real-time.

**Comment by SnaiperoG3D** [comment] 2024-07-07 19:39
Got some info about it. Im developing another game, where i have same bug i guess and this bug releated too pool nobs. I have in this game simple logic, player can eat food, food have random value which ads to player score. There are lot of food on the map so i did prewarm food nob. So as a result after despawn, and respawn, food have 0 int syncvar instead of random value. my fix above fix the issue.
https://pastebin.com/iBfGeKwA
there are 3 scipts, food spawner, food, and player eater.

**Comment by SnaiperoG3D** [comment] 2024-07-07 19:46
when i done with this project i can try to replicate this bug in simple new project. cuz now i exaclty know that it happens with this simple logic

**Comment by SnaiperoG3D** [comment] 2024-07-15 18:56
UPD: there is a final version of my fix. I reread this thread and my snippets may be not clear to understand
```c#        
internal void Deinitialize(bool asServer)
        {
#if !PREDICTION_1
            Prediction_Deinitialize(asServer);
#endif
            InvokeStopCallbacks(asServer, true);
            if (!(!asServer && (NetworkManager == null || NetworkManager.IsHostStarted)))
                for (int i = 0; i < NetworkBehaviours.Length; i++)
                    NetworkBehaviours[i].Deinitialize(asServer);

            if (asServer)
            {
                NetworkObserver?.Deinitialize(false);
                IsDeinitializing = true;
            }
            else
            {
                if (ClientManager != null)
                {
                    Dictionary<NetworkObject, NetworkConnection.LevelOfDetailData> currentLods = ClientManager.Connection.LevelOfDetails;
                    if (currentLods.TryGetValue(this, out NetworkConnection.LevelOfDetailData lodData))
                        ObjectCaches<NetworkConnection.LevelOfDetailData>.Store(lodData);
                    ClientManager.Connection.LevelOfDetails.Remove(this);
                    //Client only.
                    if (!NetworkManager.IsServerStarted)
                        IsDeinitializing = true;

                    RemoveClientRpcLinkIndexes();
                }
            }

            SetInitializedStatus(false, asServer);

            if (asServer)
                Observers.Clear();
        }

**Comment by FirstGearGames** [comment] 2024-07-18 16:38
What did you change to resolve your issue?

**Comment by SnaiperoG3D** [comment] 2024-07-21 15:10
I sent the project with a bug to DM in Discord

**Comment by NPatel10** [comment] 2024-08-04 04:26
I have face the same issue. when there is an observer system and some script which despawns an object with little time gap this bug arises. After some digging if found that two path lead to this method code. One is from server side and other from client side. Path from server side checks `NetworkObject.IsDeinitializing` to prevent second deinitialization but on client side this condition is not being checked. Therefore I added `if (IsDeinitializing) return;` statement at the top of `Deinitialize` method to prevent second deinitialization of the object.

Note: - I have no comments on below part.
`if (!(!asServer && (NetworkManager == null || NetworkManager.IsHostStarted)))
                for (int i = 0; i < NetworkBehaviours.Length; i++)
                    NetworkBehaviours[i].Deinitialize(asServer);`

**Comment by SnaiperoG3D** [comment] 2024-08-28 16:06
Reminder with files and short description
1. 2 packages with bug in this topic.
[fishHostBug2.zip](https://github.com/user-attachments/files/16785971/fishHostBug2.zip)
[fishHostBug2_fishV3.zip](https://github.com/user-attachments/files/16785972/fishHostBug2_fishV3.zip)
2. host bug with synclist
[SYncList_stacktrace.txt](https://github.com/user-attachments/files/16786016/SYncList_stacktrace.txt)
3. new host errors
[error1_stacktrace.txt](https://github.com/user-attachments/files/16786045/error1_stacktrace.txt)
[error2_stacktrace.txt](https://github.com/user-attachments/files/16786047/error2_stacktrace.txt)
nre -> mre -> then few errors from my logic. because of these two i believe
4. tugboat issue:
well i see some difference in tugboat, especially timeout now 1800sec, was 15. and set timeout method empty now. so my code doesnt make any sence now. i believe that server/client manager should do the work with timeout. but in my case its not. i have an issue when some players can connect to server about minute, so i set timeout manually for players with low end devices. and i believe that server/client manager timeout logic cant handle situation when player just colapse the game on mobile without proper exit. cuz on my servers i have a lot of "stanting" players. i believe that server manager timeout logic dont work for some reason, and game waiting for 1800sec timeout
5. _valueSetAfterInitialized issue in SyncVar.cs -> WriteFull

**Comment by SnaiperoG3D** [comment] 2024-09-03 12:49
Tested errors with FishNetworking.4.4.5R.Pro_Prerelease_02
1 Still exist
2-3 Still exist + new (maybe not new) errors happens. Hard to tell  whats gone and whats new
[2_new1.txt](https://github.com/user-attachments/files/16848808/2_new1.txt)
[2_new2.txt](https://github.com/user-attachments/files/16848809/2_new2.txt)
[2_new3.txt](https://github.com/user-attachments/files/16848850/2_new3.txt)
[2_new4.txt](https://github.com/user-attachments/files/16848852/2_new4.txt)
[2_new5.txt](https://github.com/user-attachments/files/16848854/2_new5.txt)

**Comment by FirstGearGames** [comment] 2024-09-13 18:21
We confirmed together that the Synclist issue resolved in 4.4.5. The other issue is still being looked into.

**Comment by FirstGearGames** [comment] 2024-10-05 20:47
Unable to reproduce your missing reference errors in the 4.4.8. Let me know if problem persist in that version. If it does please direct message me.

**Comment by SnaiperoG3D** [comment] 2024-10-06 11:53
> Tested errors with FishNetworking.4.4.5R.Pro_Prerelease_02 1 Still exist 2-3 Still exist + new (maybe not new) errors happens. Hard to tell whats gone and whats new [2_new1.txt](https://github.com/user-attachments/files/16848808/2_new1.txt) [2_new2.txt](https://github.com/user-attachments/files/16848809/2_new2.txt) [2_new3.txt](https://github.com/user-attachments/files/16848850/2_new3.txt) [2_new4.txt](https://github.com/user-attachments/files/16848852/2_new4.txt) [2_new5.txt](https://github.com/user-attachments/files/16848854/2_new5.txt)

so. 4.4.7Pro. there is no 4.4.8 yet
1. testing
2. no issue, even on stable
3. still exists, this is the main reason why i cant update my games to new fish versions, it just break the game
4. cant check, cuz this problem on mobile and i cant update game cuz of issue above, but timeout still 1800 in tugboat
5. no issue
6. new NRE issues. happens somewhere around as 3 issue, on disconnect on host
[new_nre1.txt](https://github.com/user-attachments/files/17269166/new_nre1.txt)
[new_nre2.txt](https://github.com/user-attachments/files/17269168/new_nre2.txt)

**Comment by FirstGearGames** [comment] 2024-10-06 17:02
Still no error in my 4.4.8 version - sent you copy to test.

**Closed** 2024-10-08 21:42 UTC
Labels: Acknowledged - Maybe Bug, Resolved Pending Testing
