### ISSUE TITLE
Adding Rigidbody runtime to NetworkObejct with NetworkTransform not sync

### ISSUE THREAD

**Issue by SnaiperoG3D** [FirstGearGames/FishNet#142] opened 2022-10-29 16:30 UTC
Situation: I have a spawner script to spawn items. Script adding to items rb to physically calculate position and rotation, after velocity 0 in some time, it remove rb. This logic works only on the server, because i dont need to add an rb to items on clients. As a result this issue appears (image)

upd: detailed description what happend on image above:
1. object spawning in the air (without rb)
2. server adds rb and waiting for velocity 0
3. server removing rb after velocity 0
4. client position never changed since it was spawned
result: on server item position was changed by physics, but on client item position never changed, it still flying in the air

example 2 (releated to 3 point about extrapolation): 
1. object spawning with rb, or rb added at awake (any unity method before fishnet calls)
2. object starts to fall on server (server authoritative)
3. object starts to fall on client
4. removing object rb on client in the process of falling
5. client object stops updating position
result: on server item position was changed by physics as in previos example, but on client item position was changed untill rb was destroyed on client and it still flying in the air, but on the middle (or when was removed rb) of way to the ground

**1.** Remove on client in OnStartClient method **WILL** reproduce issue (if was added in Awake method, because Start will called after OnStartClient, found it with practice, becase of: [script execution order](https://github.com/FirstGearGames/FishNet/issues/141) )
**2.** Adding rb on server and rpc to clients when you want to use rb runtime to add rb **WILL** reproduce issue
**3.** Also problem with extrapolation appears. I send a rpc to clients when server physics done, and i guess rpc to client called before client done with extra on intrapolation, as a result my items on client starts to fall on ground and stopping in the middle.

**Fix for it:** Add rigidbody to prefab, or add it in Awake or OnEnable or Start method. 
If object will be used in pool i guess it need to be used in OnEnable method
Because of **3** it need to add same velocity check on client, before actually remove rb.

![image](https://user-images.githubusercontent.com/88710464/198840462-b9f5c386-1700-4074-a493-5a7535b76d12.png)

**Comment by FirstGearGames** [comment] 2022-10-29 17:02
This seems more like a help question than a bug. Closing for now. Please use the Discord for help.

**Comment by SnaiperoG3D** [comment] 2022-10-29 18:18
This is a not a help question this is a problem with fishnet and flex component in mirror. This never happend with standart mirror network transform

**Comment by SnaiperoG3D** [comment] 2022-10-29 18:22
When rigidbody has been removed on client, for any reason, NT stopping to receive or change (idk how it works) its own position

**Comment by FirstGearGames** [comment] 2022-10-29 18:26
Sounds unusual, I'll read it again when I get home.

**Comment by SnaiperoG3D** [comment] 2022-10-29 18:31
ok. there is a post at Discord https://discord.com/channels/424284635074134018/1035629847969550368
i had this problem maybe a yeah ago with flex components, we had a chat about it, and i face same problem with fishnet now

**Comment by SnaiperoG3D** [comment] 2022-11-07 13:55
Hi, notice about this issue, because it still closed

**Comment by FirstGearGames** [comment] 2022-11-07 14:14
Can you please make a new project with simple scripts reproducing the issue?

**Comment by SnaiperoG3D** [comment] 2022-11-07 16:48
yeah, sure, just need some time

**Comment by SnaiperoG3D** [comment] 2022-11-15 13:15
i had to do a lot of tests, but still cant find why its happening, idk how to reproduce it in empty project, because idk whats the problem, im facing it only in fishnet and flex components. ive tryed to adding, removing rb runtime, added into prefab, etc... i have a thoughts that it might be related not to rb, but to nt themself. i found a way when its not happening:
1, as i described above i have item spawning system, it starts to work when client entered in trigger zone, item spawning in the air and then position calculating by physics.
2. if player already has been spawning and just walkin around the map, everything is ok
3. but if player spawning in this zone, problem appears
4. i have a video below with issue. player spawned at server, items starts spawning and calculating, at server everything is ok, but on client for some reason items positions not updated.
5. as you can see from hierarchy, nobs (enemies, and i guess items too) were spawned with delay on client and after positions were calculated by physics.
6. ive placed spawners few metters higher, to make a situation when items trully spawned on client when they still moving and issue gone. so it related to nt when item not moving on server

im still trying find a way to reproduce it, just notice I didn't forget about this ticket

https://user-images.githubusercontent.com/88710464/201925985-a7b830d2-e743-4122-8805-ebf1b31cad0d.mp4

**Comment by FirstGearGames** [comment] 2022-11-15 15:22
When a client spawns into the world they're sent the current pos/rot data of objects. If objects are added into the scene (not instantiated) then data is only sent if they're changed. 

Instantiated objects always have pos/rot sent.

With that said, if the objects are instantiated I do not see how they could possibly be in the wrong position because they're updated soon as the item is spawned regardless of if its moving or not.

If the broken objects are items pre-placed in the scene maybe there's something wrong with the check to only send changes, but I doubt it.

Does the problem go away if you remove the NT? I know that might go against your needs but it will help a lot in determining the cause.

**Comment by SnaiperoG3D** [comment] 2022-11-15 15:56
When should i remove NT?

**Comment by FirstGearGames** [comment] 2022-11-15 16:32
Might be related to this https://github.com/FirstGearGames/FishNet/issues/143
Currently under investigation.

Let me look at the other problem first since it's a little less complex.

**Comment by FirstGearGames** [comment] 2022-11-16 22:39
I wasn't able to reproduce in #143; I suspect that one may not actually be a bug. Let's focus on getting yours resolved. I need a few things answered just to be sure before I start testing.

1. Are these scene objects or are they instantiated at runtime?
2. Please show inspector of objects inspector expanded.
3. Can this be reproduced by connecting/disconnecting the client? EG: you said it does not occur every time, does forcing the client to rejoin the server make it easier to reproduce or are other steps required?
4. Can you please reword this, I do not understand. "5. as you can see from hierarchy, nobs (enemies, and i guess items too) were spawned with delay on client and after positions were calculated by physics."

**Comment by FirstGearGames** [comment] 2022-11-23 22:50
Resolved in 2.6.3, thank you so much for the help!

**Comment by SnaiperoG3D** [comment] 2022-11-24 10:07
your welcome. thanks for your attention to issues

**Comment by mitsh** [comment] 2022-11-24 17:26
I've faced with same issue. When will you release the fixed version?

**Comment by FirstGearGames** [comment] 2022-12-04 14:06
> I've faced with same issue. When will you release the fixed version?

I'm making a release today. 2.6.3.

**Closed** 2022-12-04 14:06 UTC
Labels: bug, Resolved
