### ISSUE TITLE
PredictedObject not updating Graphical Object when smoothing is disabled

### ISSUE THREAD

**Issue by tedbarth** [FirstGearGames/FishNet#294] opened 2023-03-13 07:32 UTC
Unity version: 2021.3.19f1
Fish-Networking version: 3.4.3

**Describe the bug**
When smoothing on a PredictedObject is turned off, e.g only for rotation, the rotation of the graphical object isn't updated at all

**To Reproduce**
1. Implement CSP with PredictedObject where the object has a collider attached to it to visualize base rotation
2. Connect with a client to a server
3. Turn off rotation smoothing for client's player on client
4. Rotate the object using inputs on the client
5. Observe the object on client while having selected the object in hierarchy

**Expected behavior**
The object and its Graphical Object child do rotate together non-interpolated.

**What you see instead**
The object rotates, but the Graphical Object does not update its rotation and is stuck at the initial rotation angle from when smoothing was disabled for rotation.

**Video**
https://youtu.be/JO_TC4KU58k

**Comment by FirstGearGames** [comment] 2023-03-13 11:19
Intended behavior. You have to smooth it when you disable smoothing.

**Comment by tedbarth** [comment] 2023-03-13 11:28
I'm not expecting that the Graphical Object moves smoothly. I expect that it does move at least stuttering with the updates of updates of the parent object, if smoothing is turned off. Instead, if smoothing is turned off for position and rotation, the graphical object is locked in position and rotation, not moving at all.

If this is intended, what use case is it where you want this behavior?
Also then, I would expect a different name, to indicate that these switches turn off updates of Graphical Object completely, not just the smoothing (interpolation).

**Comment by FirstGearGames** [comment] 2023-03-14 12:37
Closing because not a bug.
Discussions on Discord please.

**Closed by FirstGearGames** 2023-03-14 12:37 UTC
