### ISSUE TITLE
Rigidbody 2D Kinematic Issue with RigidbodyPauser and PredictedObjects

### ISSUE THREAD

**Issue by kylezimmerman** [FirstGearGames/FishNet#319] opened 2023-04-07 15:30 UTC
Unity version: 2021.3.4f1
Fish-Networking version: 3.5.8

**Describe the bug**
Been out of the loop for a bit and am updating from 2.2.5 to 3.5.8. Upgrade has been fairly straightforward so far, but I'm running into a strange behavior around RigidBody2D kinematic/dynamic state. I have a script that changes the state from dynamic to kinematic when an object is spawned. This worked fine in 2.2.5.

Now on 3.5.8 it works on the server but not on the client. I can see the `rb.isKinematic = true` line is run on the client, but the rigidbody2d ends up being reverted back to dynamic afterwards.

This is done through a `[SyncVar]`

```cs
    [SyncVar(OnChange = nameof(OnChangeHoldableState))]
    public HoldableState State = HoldableState.Item;

    private void OnChangeHoldableState(HoldableState oldState, HoldableState newState, bool asServer)
    {
        rb.isKinematic = makeKinematicWhileHolding || rb.isKinematic;
    }
```

**Expected behavior**
The `isKinematic` state should remain consistent between the client and server after the state is managed by `PredictedObject`/`RigidbodyPauser`.

**Possible fix**
I was able to fix this by modifying `Rigidbody2DState`, `RigidbodyPauser`, and `PredictedObject.Rigidbodies` to store and use `isKinematic` in addition to `isSimulated` just like for the 3D version.

**Screenshots**

**Comment by FirstGearGames** [comment] 2023-04-16 14:40
Both the 2D and 3D version re-assigns kinematic/simulated state. Here is the code from 2D.
```cs
                //Sets isKinematic status and returns if successful.
                bool UnpauseRigidbody(int index)
                {
                    Rigidbody2DData rbData = _rigidbody2dDatas[index];
                    Rigidbody2D rb = rbData.Rigidbody2d;
                    if (rb == null)
                        return false;

                    rb.velocity = rbData.Velocity;
                    rb.angularVelocity = rbData.AngularVelocity;
                    rb.simulated = rbData.Simulated;
                    rb.isKinematic = !rbData.Simulated;
                    SceneManager.MoveGameObjectToScene(rb.transform.root.gameObject, rbData.SimulatedScene);
                    return true;
                }
```
Are you referencing a different part of code?

**Comment by kylezimmerman** [comment] 2023-04-16 15:59
The 2D version does assign `isKinematic` but from `!rbData.Simulated` but `isKinematic` and `Simulated` are not opposites like this. They are two independent properties (ie a rigidbody2d can be simulated dynamic, simulated kinematic, not simulated dynamic, not simulated kinematic, etc.).

Currently FishNet stores only the `Simulated` value in the Rigidbody2DState and sets `isKinematic` to the opposite, but this means it takes an object with `Simulated == true and isKinematic == true` and restores it as  `Simulated == true and isKinematic == false` which is incorrect and results in clients getting kinematic rigidbodies turned into dynamic ones.

What I changed to fix it was to additionally add `isKinematic` to:

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Generated/Component/Prediction/RigidbodyState.cs#L38

```cs
public bool isKinematic;

// Add this in both constructors
isKinematic = rb.isKinematic;

// Add writer.WriteBoolean() and reader.ReadBoolean() in the serializer
```

And in In https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Generated/Component/Prediction/RigidbodyPauser.cs#L279 Change 
```cs
                bool UnpauseRigidbody(int index)
                {
                    Rigidbody2DData rbData = _rigidbody2dDatas[index];
                    Rigidbody2D rb = rbData.Rigidbody2d;
                    if (rb == null)
                        return false;

                    rb.velocity = rbData.Velocity;
                    rb.angularVelocity = rbData.AngularVelocity;
                    rb.simulated = rbData.Simulated;
                    rb.isKinematic = !rbData.Simulated;
                    SceneManager.MoveGameObjectToScene(rb.transform.root.gameObject, rbData.SimulatedScene);
                    return true;
                }
```

```cs
// before
rb.simulated = rbData.Simulated;
rb.isKinematic = !rbData.Simulated;

// after
rb.simulated = rbData.Simulated;
rb.isKinematic = rbData.isKinematic;
```

Similarly here in PredictedObject.Rigidbodies:

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Generated/Component/Prediction/PredictedObject.Rigidbodies.cs#L363

https://github.com/FirstGearGames/FishNet/blob/main/Assets/FishNet/Runtime/Generated/Component/Prediction/PredictedObject.Rigidbodies.cs#L1038

There may be other areas where this same isKinematic == !Simulated assumption was made, but these changes fixed the bug I was seeing.

**Comment by FirstGearGames** [comment] 2023-04-16 16:49
Got it. Going by the documentation it seemed as though they were the same. I do know you can set kinematic and the object still be simulated, so that further validates what you're saying.

If the issue is only with Rigidbody2D, which it sounds as though that's the case, I don't think I'll need a PR. I'll get it sorted, thanks!

**Comment by kylezimmerman** [comment] 2023-04-16 16:56
Agreed, the wording on the Official Unity Docs for these properties is absolutely terrible and I can 100% understand why you'd have thought they were the same.

As far as I know this only applies to Rigidbody2D, I don't think 3D Rigidbody has the concept of "simulated" at all.

Thanks for looking into resolving it for future versions!

**Comment by FirstGearGames** [comment] 2023-04-20 14:06
Resolved in 3.6.3

**Comment by kylezimmerman** [comment] 2023-05-09 22:55
Updated from 3.5.8.Pro to 3.6.9.Pro and this issue doesn't appear to be fixed. Sorry for the late re-open, I didn't have a chance to investigate until today.

I went through the code and had to reapply a few parts of my patch in certain places:

### FishNet\Runtime\Generated\Component\Prediction\PredictedObject.Rigidbodies.cs

#### Before:

```cs
                if (_preReplicateReplayCacheIndex != -1)
                {
                    bool prevSimulated = _rigidbody2dStates[_preReplicateReplayCacheIndex].Simulated;
                    _rigidbody2d.simulated = prevSimulated;
                    _rigidbody2d.isKinematic = !prevSimulated;
                }
```

and in `ResetRigidbody2DToData`

```cs
            _rigidbody2d.isKinematic = !simulated;
```

#### After:
```cs
                if (_preReplicateReplayCacheIndex != -1)
                {
                    var prevState = _rigidbody2dStates[_preReplicateReplayCacheIndex];
                    _rigidbody2d.simulated = prevSimulated;
                    _rigidbody2d.isKinematic = prevKinematic;
                }
```

and in `ResetRigidbody2DToData`:

```cs
            _rigidbody2d.isKinematic = state.IsKinematic;
```

### FishNet\Runtime\Generated\Component\Prediction\RigidbodyState.cs

In `WriteRigidbody2DState()`
#### Before:
```cs
        writer.WriteBoolean(!value.IsKinematic);
```

#### After:
```cs
        writer.WriteBoolean(value.IsKinematic);
```

**Comment by FirstGearGames** [comment] 2023-05-10 17:06
Saw your comment come through my email but couldn't find it because issue was closed. Going to apply your fixes and have them in the next release.

**Closed** 2023-05-17 18:26 UTC
Labels: Resolved Pending Release
