### ISSUE TITLE
Problem about reconnect after a short disconnection

### ISSUE THREAD

**Issue by mertepsileli-lp** [FirstGearGames/FishNet#470] opened 2023-09-28 18:04 UTC
# Important
If General, Description, and Replication are not completed the issue will be closed immediately.

**General**
Unity version: 2021.3.25f1
Fish-Networking version: 3.11.2R Pro
Discord link: https://discord.com/channels/424284635074134018/1156910923458547833/1156910923458547833

**Description**
I am using a dedicated server (Azure Server). I was using FN version 2.6.4, and when I turned off the Wi-Fi on the client and after a few seconds turned it on, the client stayed online. I updated FN version to 3.11.2R Pro. Now, when I turn the Wi-Fi off and turn it on after a few seconds, the client calls OnStopClient together with "PeerNotFound" warning (You can look at Images 1-2), and all network objects on the client are destroyed, only the network manager stays alive. The client socket is stopped on the client, however, the server does not destroy the client instance until the end of the timeout. Shortly, when I disconnect the client, everything about the network is destroyed (except the network manager) on the client, and nothing changes on the server until the end of the timeout. When I wrote a code to reconnect the client to the server, a new clientID and new client instance were created (You can look at Image 3 for the code.) I also tried versions 3.5.8 and 3.7.4, I experienced the same problem.
**I tried a lot of versions of FN, this problem starts with version 3.5.1. 3.5.0 and older versions working well.

**Replication**
1. Build as Linux Dedicated Server and run it on an online server.
2. Open the game on Unity Editor on another computer (use a different computer because we will turn the Wi-Fi off).
3. Run the game on Editor and start the connection.
4. Turn the Wi-Fi off and turn it on after a few seconds.
5. The client instance and all network objects will be destroyed and the client socket will stop.
6. If you do the same things with version 2.6.4, nothing will be destroyed and the client socket will continue to work.

**Expected behavior**
I expect that if a client disconnects and reconnects before timeout passes, the client should use the same network connection, and the client ID and client instance should not change. OnStopClient callbacks should not be called.

**Screenshots**
![Image 1](https://github.com/FirstGearGames/FishNet/assets/91895570/a620090d-c696-4493-929e-fafadd433e0b)
![Image 2](https://github.com/FirstGearGames/FishNet/assets/91895570/96c54f27-8b5a-4fcf-a7b4-969c07b9b232)
![Image 3](https://github.com/FirstGearGames/FishNet/assets/91895570/e8edba2f-6f44-40aa-a30b-b60e99f36645)

**Comment by FirstGearGames** [comment] 2023-10-02 15:43
I will look into the PeerNotFound warning but the rest sounds to be working as intended.
If a client connection drops all objects should be destroyed, and they should be assigned a new Id upon reconnecting.

Note that simply pausing the WiFi is not the same as dropping a connection. It's entirely possible for the client to remain  connected even with WiFi paused so long as the socket does not time out nor the server kick the client.

Have you already looked at the servermanager/clientmanager timeout settings by any chance?

**Comment by mertepsileli-lp** [comment] 2023-10-02 15:57
This is my ServerManager and ClientManager settings. Yes if the connection drops, all objects should destroyed. As I said, in the old version, Wi-Fi does not cause connection drops, but it is not the same in version 3.5.1 and later.
In addition, in Android build closing the game does not cause dropping the connection from the server. It is dropped after the time-out ends. However, it works as expected in the IOS build. When I close the game, the connection drops from the server immediately. Maybe something is broken in Tugboat script.
![Ekran Resmi 2023-10-02 18 48 47](https://github.com/FirstGearGames/FishNet/assets/91895570/9f733042-5665-4b54-9481-7343b92f46a4)

**Comment by FirstGearGames** [comment] 2023-10-06 14:56
Okay, I have a suspicion I know what this is about. Awhile ago there was a change to LNL to fix a mobile issue. The changed file was PausedSocketFix; it was added/modified and implemented. Let me start there and get back to you.

**Comment by FirstGearGames** [comment] 2023-10-06 15:00
In PausedSocketFix return at the top of TryReconnect to see if that fixes your problem.
Like so...
```cs
        private void TryReconnect()
        {
            return;
```
If that works I'll investigate options.

**Comment by FirstGearGames** [comment] 2023-10-06 15:25
Please import and test this for me. It uses a combination of the old method with new.
[FN 3.11.3 LNL Test.zip](https://github.com/FirstGearGames/FishNet/files/12832791/FN.3.11.3.LNL.Test.zip)

**Comment by mertepsileli-lp** [comment] 2023-10-06 15:29
How can I import and test this file? Btw, I am using MacOS.

**Comment by mertepsileli-lp** [comment] 2023-10-06 15:32
There is not a .unitypackage file inside the zip can you check it?

![Ekran Resmi 2023-10-06 18 32 48](https://github.com/FirstGearGames/FishNet/assets/91895570/39896572-cbb0-4eac-a186-99af38a804c7)

**Comment by FirstGearGames** [comment] 2023-10-06 15:47
There is, your Mac is just being a Mac :P
Try this https://firstgeargames.com/FN%203.11.3%20LNL%20Test.unitypackage

**Comment by mertepsileli-lp** [comment] 2023-10-06 16:05
Thanks :D I will test and inform you in short time.

**Comment by FirstGearGames** [comment] 2023-10-06 20:38
Going to send 3.11.3 up over the weekend so I can resume v4. If possible please let me know by the end of tomorrow so I can get the changes in(if the resolve).

**Comment by mertepsileli-lp** [comment] 2023-10-06 20:42
Hi again, I tested many cases. 
-Firstly, if I import .unitypackage, I cannot connect to server, so I cannot test anything. In fact server does not start as localhost.

-When I changed PausedSocketFix.cs as you said (you can see in the image below), the disconnection problem which occurs when disabled-enabled Wi-Fi for a short time, has been solved. The client does not disconnect until end of time-out. 

-In IOS if client exits the game, server kicks the client immediately. If client disables-enables Wi-Fİ quickly, he can reconnect as usual and if the client exit the game after reconnection, server kick him immediately as expected. However, if the client disables Wi-Fi and waits more than 10-15 seconds before enabling it, he can still reconnect to game as usual but if he exits the game, server does not kick him immediately. The server waits for the end of the timeout.

-In Android, the reconnection problem also has been solved. If the client disables and enables Wi-Fi before timeout, he can reconnect as expected and continue to the game. However, when the client exits the game, server does not kick him immediately in any situation. He stays in the server until the end of the timeout.

![Ekran Resmi 2023-10-06 23 09 58](https://github.com/FirstGearGames/FishNet/assets/91895570/f7751cb4-e22f-4f36-a2bf-742979f7869c)

**Comment by FirstGearGames** [comment] 2023-10-06 20:45
Not kicking on app close is unavoidable. If the mobile platform is not sending a disconnect then the timeout is going to have to do.

Great that the return fixed it but not great really because it's not a fix, it breaks the automatic reconnect. Let me examine the changes I made again and look at getting you a new test package.

**Comment by FirstGearGames** [comment] 2023-10-06 21:24
Issue is it's trying to create a GO on a thread. I'm resolving it now and will get you a new update shortly.

**Comment by FirstGearGames** [comment] 2023-10-06 21:43
Try this one out  https://firstgeargames.com/FN%203.11.3%20LNL%20Test01.unitypackage

**Comment by mertepsileli-lp** [comment] 2023-10-06 22:21
I tried it however it returned to the version with reconnection problem. When I enabled-disabled Wi-Fi quickly in mobile, client disconnects locally and cannot continue to play. However, in this version the problem is solved in UnityEditor. In old version, I had the problem in UnityEditor, too. I can disable-enable Wi-Fi in UnityEditor without ant problem.

**Comment by FirstGearGames** [comment] 2023-10-06 23:16
Okay. I'm not entirely sure why this is happening in later versions and not older versions. The code is pretty much the same but with some extra sanity checks, which would if anything prevent incorrect reconnects. Here is the old code that was checked when your application was back in focus...
```cs

        private void OnApplicationPause(bool pause)
        {
            if (Socket == null)
                return;
            if (pause)
            {
                Paused = true;
                Socket.CloseSocket(true);
            }
            else if (Paused)
            {
                if (!Socket.Start(BindAddrIPv4, BindAddrIPv6, Port, ManualMode))
                {
                    NetDebug.WriteError("[S] Cannot restore connection \"{0}\",\"{1}\" port {2}", BindAddrIPv4, BindAddrIPv6, Port);
                    Socket.CloseSocket(false);
                }
            }
        }
```
As you can see it was actually closing the socket.

The new code is this...
```cs
        private void OnApplicationPause(bool pause)
        {
            if (!pause && Core != null)
                Core.TryReconnect();
        }

        public void TryReconnect()
        {
            if (NetManager == null)
                return;
            //Was intentionally disconnected at some point.
            if (!NetManager.IsRunning)
                return;
            if (!NetManager.IsClient)
                return;
            //Socket is still running.
            if (NetManager.SocketActive(false) || NetManager.SocketActive(true))
                return;

            //Socket isn't running but should be. Try to start again.
            if (!NetManager.Start(_ipv4, _ipv6, _port, _manualMode))
            {
                NetDebug.WriteError($"[S] Cannot restore connection. Ipv4 {_ipv4}, Ipv6 {_ipv6}, Port {_port}, ManualMode {_manualMode}");
                NetManager.CloseSocket(false);
            }
        }
```
You can see it aborts the reconnect under a number of conditions, which if anything should be more reliable. There is one thing left to try that might make it behave as expected...

Open PausedSocketFixCore.cs and change to...
```cs
   public class PausedSocketFixCore
    {
        public bool Paused { get; private set; }
        public NetManager NetManager { get; private set; }
        private IPAddress _ipv4;
        private IPAddress _ipv6;
        private int _port;
        private bool _manualMode;

        public PausedSocketFixCore() { }
        public void Initialize(NetManager netManager, IPAddress ipv4, IPAddress ipv6, int port, bool manualMode)
        {
            NetManager = netManager;
            _ipv4 = ipv4;
            _ipv6 = ipv6;
            _port = port;
            _manualMode = manualMode;
        }

        public void SetPaused(bool paused)
        {
            Paused = paused;
        }

        public void TryReconnect()
        {
            if (!Paused)
                return;
            if (NetManager == null)
                return;
            //Was intentionally disconnected at some point.
            if (!NetManager.IsRunning)
                return;
            if (!NetManager.IsClient)
                return;
            //Socket is still running.
            if (NetManager.SocketActive(false) || NetManager.SocketActive(true))
                return;

            //Socket isn't running but should be. Try to start again.
            if (!NetManager.Start(_ipv4, _ipv6, _port, _manualMode))
            {
                NetDebug.WriteError($"[S] Cannot restore connection. Ipv4 {_ipv4}, Ipv6 {_ipv6}, Port {_port}, ManualMode {_manualMode}");
                NetManager.CloseSocket(false);
            }
        }
```

Change PausedSocketFixMono.cs to this...
```cs
    public class PausedSocketFixMono : MonoBehaviour, IPausedSocketFix
    {
        public PausedSocketFixCore Core { get; private set; }

        private void OnApplicationPause(bool pause)
        {
            if (!pause && Core != null)
                Core.TryReconnect();
            Core?.SetPaused(pause);
        }

        public void Initialize(NetManager netManager, IPAddress ipv4, IPAddress ipv6, int port, bool manualMode)
        {
            if (Core == null)
                Core = new PausedSocketFixCore();

            Core.Initialize(netManager, ipv4, ipv6, port, manualMode);
        }

        private void Update()
        {
            if (Core != null && Core.NetManager == null)
                DestroyImmediate(this);
        }
    }
```
Lastly change PausedSocketFix.cs to this...
```cs

    public class PausedSocketFix : IPausedSocketFix
    {
        public PausedSocketFixCore Core { get; private set; }

        public PausedSocketFix()
        {
            UnityEngine.Application.focusChanged += Application_focusChanged;
        }
        ~PausedSocketFix()
        {
            UnityEngine.Application.focusChanged -= Application_focusChanged;
        }

        public void Initialize(NetManager netManager, IPAddress ipv4, IPAddress ipv6, int port, bool manualMode)
        {
            if (Core == null)
                Core = new PausedSocketFixCore();

            Core.Initialize(netManager, ipv4, ipv6, port, manualMode);
        }

        private void Application_focusChanged(bool focused)
        {
            if (focused)
                Core?.TryReconnect();
            Core?.SetPaused(!focused);
        }

    }
```

**Comment by FirstGearGames** [comment] 2023-10-07 13:38
If this does not resolve the problem it's more than likely a limitation of LNL, or possibly the mobile platform. These code changes are identical to the previous FN versions with more blocks on the reconnect (meaning, less likely to incorrectly reconnect).

If the problem is not resolved I can do very little because all these checks test to see if the socket is active or not, and only tries to reconnect if it's returning as not active. The only other solution would be to not automatically reconnect and let the client timeout do it's thing. This would require players to wait the full timeout, and if dev overrode timeout in ClientManager the app may never reconnect.

**Comment by mertepsileli-lp** [comment] 2023-10-07 13:50
Thanks, I am trying these now and I will inform you.

**Comment by mertepsileli-lp** [comment] 2023-10-07 14:35
I tried, but it still does not work. I get "PausedSocketFixMono does not exist when it is expected to. Falling back to PausedSocketFix." warning in the dedicated server. Can this warning cause something?
When I wrote return at the beginning of TryReconnect, it worked as I said. What does this TryReconnect do? What happens if I write return at the beginning of this method?

**Comment by mertepsileli-lp** [comment] 2023-10-07 16:12
I found the line disconnects the client when Wi-Fi is enabled and disabled. I am writing the pat
1.) TryReconnect -> NetManager.Start in PausedSocketFix.cs
2.) NetManager.Start method starts the SocketThreadv6 with ReceiveLogic parameter.
3.) When the client enabled-disabled the Wi-Fi OnMessageReceived() is called in NetManager.cs.
4.) After that the part in the image below causes the disconnection. In the first message, it enters "if(packet.Size == 1)" and calls "SendRaw(NetConnectAcceptPacket.MakeNetworkChanged(), remoteEndPoint)".
5.) After that another message is received and this time it enters " else if (packet.Size == 2 && packet.RawData[1] == 1)" and calls "DisconnectPeerForce()" and the client is disconnected.
Do you have any idea about this?
![Ekran Resmi 2023-10-07 19 06 56](https://github.com/FirstGearGames/FishNet/assets/91895570/8478deed-2c86-4294-9736-5e977afe5575)

**Comment by FirstGearGames** [comment] 2023-10-08 18:05
It seems perhaps a LNL update changed the behavior. Because when I made the change to the pauser was also the time LNL updated. If returning out of the method fixed the issue you MIGHT just be aborting a disconnect before a reconnect. The disconnect could be why you are seeing the packets (just a theory).

The pauser came into existence before there was a server and client timeout. I think I'm just going to remove it entirely and let FN handle the timeout.

**Comment by FirstGearGames** [comment] 2023-10-08 18:09
Delete Tugboat folder and import this then try again. This removes the paused socket fix entirely.
https://firstgeargames.com/FN%203.11.3%20LNL%20Test02.unitypackage

**Comment by FirstGearGames** [comment] 2023-10-09 10:08
I'm going to mark this as resolved pending release.

At the very least, the manager timeouts will replace the PausedSocketFix code.

**Comment by mertepsileli-lp** [comment] 2023-10-10 07:52
This package solved many problems. Only Android is not kicked from the server when the app is closed. However, like you said it can be unavoidable. I wanted to inform you that there is a compilation error in the script below. I commented out all the script. Thank you, have a nice day.
![Ekran Resmi 2023-10-10 10 50 49](https://github.com/FirstGearGames/FishNet/assets/91895570/7908c921-fc6a-4cee-9aee-b03b640423bd)

**Closed** 2023-10-13 18:08 UTC
Labels: Bug, Resolved Pending Release
