### ISSUE TITLE
"Spawned NetworkObject was expected to exist" warning when despawning players on Pv2

### ISSUE THREAD

**Issue by LiamBoog** [FirstGearGames/FishNet#541] opened 2023-11-08 18:28 UTC
**General**
Unity version: 2.22.2.19
Fish-Networking version: 3.11.6
Discord link: https://discord.com/channels/424284635074134018/1170104943307395193/1170104943307395193

**Description**
Whenever a player NetworkObject gets despawned, other remote clients get the following warning before the object is destroyed locally for them: "Spawned NetworkObject was expected to exist but does not for Id [despawned ObjectId]. This may occur if you sent a NetworkObject reference which does not exist, be it destroyed or if the client does not have visibility."

**Replication**
1. Start at least 2 remote clients (not including the host) and give them ownership of a player NetworkObject
2. Despawn one of the players
3. The client(s) that wasn't despawned sees the warning

**Expected behavior**
The player NetworkObject should despawn for all clients with no warning.

**Comment by FirstGearGames** [comment] 2023-11-08 20:47
Notes: this is caused by a replicate RPC being read on the object during the despawn tick, after the despawn.

**Comment by FirstGearGames** [comment] 2023-11-21 00:54
Resolved in 4.0.3

**Closed** 2023-11-21 15:28 UTC
Labels: Bug, Resolved Pending Release
