### ISSUE TITLE
Sending Bytes array through RPC or Broadcast receives wrong byte array length.

### ISSUE THREAD

**Issue by DanielSnd** [FirstGearGames/FishNet#103] opened 2022-09-12 13:16 UTC
Sending a byte[] through an RPC or Broadcast results in receiving a byte array with the wrong array length. (2x the length in Tugboat, 1.67x or so length in Yak)

It can be reproduced with the following code, just drop it in a gameobject, connect a server and client (can be the same unity editor) and run the method SnedBytes() (Added a context menu to trigger more easily)

`using FishNet;
using FishNet.Object;
using UnityEngine;

public class ByteArrayBugReproduction : NetworkBehaviour
{

    [ServerRpc]
    public void ServerReceiveBytes(byte[] bytes)
    {
        Debug.Log($"Received on server bytes length {bytes.Length}");
    }
    
    [ObserversRpc]
    public void ClientReceiveBytes(byte[] bytes)
    {
        Debug.Log($"Received on client bytes length {bytes.Length}");
    }

    [ContextMenu("Send Bytes")]
    public void SendBytes()
    {
        byte[] newByteArray = new byte[100000];
        if (InstanceFinder.IsServer)
        {
            Debug.Log($"Sending bytes length {newByteArray.Length} to client");
            ClientReceiveBytes(newByteArray);
        }
        else
        {
            Debug.Log($"Sending bytes length {newByteArray.Length} to server");
            ServerReceiveBytes(newByteArray);
        }
    }
}
`

**Comment by FirstGearGames** [comment] 2022-09-12 21:57
Confirmed, thank you.

**Comment by FirstGearGames** [comment] 2022-09-12 22:34
This error was caused by read allocated using a pooled byte array instead of a new one, resulting in the wrong array size. This has been fixed and released in 2.4.4.

Please send me a DM in my server when you have a chance.

**Closed by FirstGearGames** 2022-09-12 22:34 UTC
Labels: bug, Resolved
